import 'package:gemify/shop/gem_modal.dart';

final List<Gem> gemsList = [
  Gem(
    name: "Blue Sapphire",
    price: "\$2500",
    description:
        "Premium Ceylon Blue Sapphire known for its vivid royal blue color and brilliance. A timeless choice for fine jewelry.",
    image: "assets/images/gem_sample.png",
    weight: 5.10,
    clarity: "Loupe clean",
    size: "10.8x8.7 mm",
    color: "Royal Blue",
    shapeAndCut: "Oval Mixed Cut",
    origin: "Sri Lanka (Ceylon)",
    heated: "No",
    certificate: "GIA",
  ),
  Gem(
    name: "Padparadscha Sapphire",
    price: "\$4800",
    description:
        "Extremely rare pinkish-orange sapphire from Sri Lanka, symbolizing the colors of the lotus flower.",
    image: "assets/images/gem_sample.png",
    weight: 3.25,
    clarity: "Eye clean",
    size: "8.5x7.2 mm",
    color: "Pinkish-Orange",
    shapeAndCut: "Cushion Cut",
    origin: "Sri Lanka (Ceylon)",
    heated: "No",
    certificate: "GIA",
  ),
  Gem(
    name: "Star Sapphire",
    price: "\$950",
    description:
        "A stunning blue star sapphire displaying a sharp six-rayed star under direct light. Perfect collector’s gem.",
    image: "assets/images/gem_sample.png",
    weight: 6.40,
    clarity: "Translucent",
    size: "11.2x9.8 mm",
    color: "Cornflower Blue",
    shapeAndCut: "Cabochon",
    origin: "Sri Lanka (Ceylon)",
    heated: "No",
    certificate: "IGI",
  ),
  Gem(
    name: "Pink Sapphire",
    price: "\$1700",
    description:
        "Elegant pink sapphire with vibrant saturation and sparkling brilliance. Ideal for engagement rings.",
    image: "assets/images/gem_sample.png",
    weight: 3.10,
    clarity: "Eye clean",
    size: "9x7 mm",
    color: "Vivid Pink",
    shapeAndCut: "Oval",
    origin: "Sri Lanka (Ceylon)",
    heated: "Yes (Low heat)",
    certificate: "GIA",
  ),
  Gem(
    name: "Yellow Sapphire",
    price: "\$1200",
    description:
        "Natural Ceylon yellow sapphire with a bright golden tone, known to bring prosperity and success.",
    image: "assets/images/gem_sample_4.png",
    weight: 4.35,
    clarity: "Loupe clean",
    size: "10.5x8.3 mm",
    color: "Golden Yellow",
    shapeAndCut: "Oval Step Cut",
    origin: "Sri Lanka (Ceylon)",
    heated: "Yes (Traditional)",
    certificate: "GIA",
  ),
  Gem(
    name: "Ruby",
    price: "\$2900",
    description:
        "Deep red ruby with exceptional fire and luster. Mined and polished in Sri Lanka, ideal for luxury jewelry.",
    image: "assets/images/gem_sample_2.png",
    weight: 2.85,
    clarity: "Eye clean",
    size: "8.2x6.5 mm",
    color: "Pigeon Blood Red",
    shapeAndCut: "Oval Brilliant",
    origin: "Sri Lanka (Ceylon)",
    heated: "Yes",
    certificate: "GIA",
  ),
  Gem(
    name: "Emerald",
    price: "\$2200",
    description:
        "Vibrant green emerald with minor inclusions, offering high transparency and natural beauty.",
    image: "assets/images/gem_sample_3.png",
    weight: 4.65,
    clarity: "Slightly included",
    size: "10.9x8.1 mm",
    color: "Vivid Green",
    shapeAndCut: "Emerald Step Cut",
    origin: "Colombia",
    heated: "No (Oiled)",
    certificate: "GIA",
  ),
  Gem(
    name: "Alexandrite",
    price: "\$3800",
    description:
        "Rare color-change gemstone showing green in daylight and reddish-purple under incandescent light.",
    image: "assets/images/gem_sample.png",
    weight: 2.20,
    clarity: "Eye clean",
    size: "8.3x6.9 mm",
    color: "Bluish Green to Reddish Purple",
    shapeAndCut: "Oval Mixed Cut",
    origin: "Sri Lanka (Ceylon)",
    heated: "No",
    certificate: "GIA",
  ),
  Gem(
    name: "White Sapphire",
    price: "\$950",
    description:
        "Brilliant colorless sapphire that sparkles like a diamond, perfect for minimalistic jewelry lovers.",
    image: "assets/images/gem_sample.png",
    weight: 3.60,
    clarity: "Loupe clean",
    size: "9.5x7.5 mm",
    color: "Colorless",
    shapeAndCut: "Round Brilliant",
    origin: "Sri Lanka (Ceylon)",
    heated: "Yes (Low heat)",
    certificate: "IGI",
  ),
  Gem(
    name: "Green Tourmaline",
    price: "\$600",
    description:
        "Natural green tourmaline with fine luster and crystal clarity, a gemstone of growth and vitality.",
    image: "assets/images/gem_sample.png",
    weight: 5.40,
    clarity: "Eye clean",
    size: "12x9 mm",
    color: "Forest Green",
    shapeAndCut: "Emerald Cut",
    origin: "Sri Lanka (Ceylon)",
    heated: "No",
    certificate: "IGI",
  ),
];
