import 'package:gemify/shop/gem_modal.dart';

final List<Gem> gemsList = [
  Gem(
    name: "Blue Sapphire",
    price: "\$1200",
    description: "High-quality blue sapphire from Sri Lanka.",
    image: "assets/images/gem_sample.png",
    weight: 4.20,
    clarity: "Loupe clean",
    size: "13x9.7 mm",
    color: "Purplish Blue to Purplish Red",
    shapeAndCut: "Oval step",
    origin: "Sri Lanka",
    heated: "No",
    certificate: "GIA",
  ),
  Gem(
    name: "Red Ruby",
    price: "\$900",
    description: "Beautiful red ruby, perfect for jewelry.",
    image: "assets/images/gem_sample_2.png",
    weight: 3.50,
    clarity: "Eye clean",
    size: "12x8 mm",
    color: "Deep Red",
    shapeAndCut: "Oval",
    origin: "Sri Lanka",
    heated: "Yes",
    certificate: "GIA",
  ),
  Gem(
    name: "Emerald",
    price: "\$1500",
    description: "Premium emerald from Sri Lanka.",
    image: "assets/images/gem_sample_3.png",
    weight: 5.00,
    clarity: "Loupe clean",
    size: "14x10 mm",
    color: "Green",
    shapeAndCut: "Emerald step",
    origin: "Sri Lanka",
    heated: "No",
    certificate: "GIA",
  ),
  Gem(
    name: "Yellow Sapphire",
    price: "\$1100",
    description: "Brilliant yellow sapphire for special occasions.",
    image: "assets/images/gem_sample_4.png",
    weight: 4.00,
    clarity: "Eye clean",
    size: "13x9 mm",
    color: "Bright Yellow",
    shapeAndCut: "Oval",
    origin: "Sri Lanka",
    heated: "Yes",
    certificate: "GIA",
  ),
  // Add more gems here
];
