// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHxjlfSlk3BEDQbWhKS5mPEI4WjrOwUZc',
    appId: '1:870049339274:web:49ba50b0032f24c5589a73',
    messagingSenderId: '870049339274',
    projectId: 'e-shop-vid-da4a3',
    authDomain: 'e-shop-vid-da4a3.firebaseapp.com',
    storageBucket: 'e-shop-vid-da4a3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHKOwbJmq8nJXg7GQ83ByNqPpE64ip5VU',
    appId: '1:867553853394:android:87dd4a805bf0493b33120b',
    messagingSenderId: '867553853394',
    projectId: 'gemify-app',
    databaseURL: 'https://gemify-app-default-rtdb.firebaseio.com',
    storageBucket: 'gemify-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX5H4nPTnoOEPFb-eWX9JKXuUdkAVYrgU',
    appId: '1:867553853394:ios:99ca74146bb0099733120b',
    messagingSenderId: '867553853394',
    projectId: 'gemify-app',
    databaseURL: 'https://gemify-app-default-rtdb.firebaseio.com',
    storageBucket: 'gemify-app.firebasestorage.app',
    iosBundleId: 'com.example.gemifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX5H4nPTnoOEPFb-eWX9JKXuUdkAVYrgU',
    appId: '1:867553853394:ios:99ca74146bb0099733120b',
    messagingSenderId: '867553853394',
    projectId: 'gemify-app',
    databaseURL: 'https://gemify-app-default-rtdb.firebaseio.com',
    storageBucket: 'gemify-app.firebasestorage.app',
    iosBundleId: 'com.example.gemifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIe0Ncl9kJ9NrT14o2mWPXDD8X11KKFOM',
    appId: '1:870049339274:web:ba586c94bfe165f1589a73',
    messagingSenderId: '870049339274',
    projectId: 'e-shop-vid-da4a3',
    authDomain: 'e-shop-vid-da4a3.firebaseapp.com',
    storageBucket: 'e-shop-vid-da4a3.appspot.com',
  );
}